"""Shared helpers for the replay experiments (E2-E10): CIs, buckets, policies, reports.

Conventions (docs/TEST_MATRIX.md):
  * inference clusters by settlement event: every CI here is an event-level (cluster) bootstrap
    of a contract-weighted mean, seeded;
  * every P&L table carries a ``policy`` column; fill policies A (optimistic), B (realistic),
    C (conservative); A is reported for reference only and a result that holds only under A is
    flagged (``flag_only_A``);
  * reports on synthetic recordings carry the banner ``SYNTHETIC_BANNER`` and are never
    evidence of edge.

Units: money in dollars, per-contract edges in cents per contract (``_c`` suffix), times in ns.
"""

from __future__ import annotations

import calendar
import math
import re
import subprocess
import time
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from dh.core.units import NS_PER_S

SYNTHETIC_BANNER = "SYNTHETIC DATA — pipeline validation only"
SYNTHETIC_NOTE = (
    f"> **{SYNTHETIC_BANNER}.** The recording was generated by `dh.research.synth_recording` "
    "(dh.sim.synthetic with injected effects). Numbers validate that the pipeline runs end to "
    "end and recovers injected effects; they are NOT evidence of edge on Kalshi."
)
REPO = Path(__file__).resolve().parents[2]

# ----------------------------------------------------------------------------- fill policies
POLICY_NAMES = {"A": "optimistic", "B": "realistic", "C": "conservative"}
POLICY_LETTER = {v: k for k, v in POLICY_NAMES.items()}


def policy_letter(p: str) -> str:
    """'realistic' | 'B' | 'b' -> 'B'."""
    s = p.strip()
    if s.upper() in POLICY_NAMES:
        return s.upper()
    try:
        return POLICY_LETTER[s.lower()]
    except KeyError:
        raise ValueError(f"unknown fill policy {p!r} (use A/B/C)") from None


def parse_policies(s: str | Sequence[str]) -> list[str]:
    """'B,C' | ['A','B'] -> ['B', 'C'] (letters, de-duplicated, order kept)."""
    items = s.split(",") if isinstance(s, str) else list(s)
    out: list[str] = []
    for x in items:
        if x.strip():
            L = policy_letter(x)
            if L not in out:
                out.append(L)
    return out


# ----------------------------------------------------------------------------- time
_ISO = re.compile(r"^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2})(?::(\d{2})(?::(\d{2})(\.\d+)?)?)?)?Z?$")


def parse_time(s: str | int | None, default: int | None = None) -> int:
    """ISO-8601 UTC ('2026-09-25T12:00', '2026-09-25') or epoch s/ms/us/ns (by magnitude) -> ns."""
    if s is None or s == "":
        if default is None:
            raise ValueError("time required")
        return default
    if isinstance(s, (int, np.integer)):
        return _epoch_to_ns(float(s), str(s))
    txt = str(s).strip()
    if re.fullmatch(r"-?\d+(\.\d+)?", txt):
        return _epoch_to_ns(float(txt), txt)
    m = _ISO.match(txt)
    if not m:
        raise ValueError(f"cannot parse time {s!r}")
    y, mo, d, h, mi, sec, frac = m.groups()
    secs = calendar.timegm((int(y), int(mo), int(d), int(h or 0), int(mi or 0), int(sec or 0), 0, 0, 0))
    ns = int(frac[1:].ljust(9, "0")[:9]) if frac else 0
    return secs * NS_PER_S + ns


def _epoch_to_ns(x: float, txt: str) -> int:
    if abs(x) > 1e17:
        return int(txt) if re.fullmatch(r"-?\d+", txt) else int(x)
    if abs(x) > 1e14:
        return int(round(x * 1e3))
    if abs(x) > 1e11:
        return int(round(x * 1e6))
    return int(round(x * 1e9))


def fmt_ns(t: int | None) -> str:
    if not t:
        return "-"
    s, ns = divmod(int(t), NS_PER_S)
    return time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(s)) + f".{ns // 1_000_000:03d}Z"


# ----------------------------------------------------------------------------- buckets
TAU_EDGES_S = (0.0, 30.0, 60.0, 300.0, 600.0, 1800.0, math.inf)
TAU_LABELS = ("<30s", "30-60s", "1-5m", "5-10m", "10-30m", ">30m")  # TEST_MATRIX regime split
Z_EDGES = (0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, math.inf)
Z_LABELS = ("0-0.5", "0.5-1", "1-1.5", "1.5-2", "2-2.5", "2.5-3", ">3")
PRICE_EDGES_C = (0.0, 5.0, 10.0, 25.0, 50.0, 75.0, 90.0, 95.0, 100.01)
PRICE_LABELS = ("1-5c", "5-10c", "10-25c", "25-50c", "50-75c", "75-90c", "90-95c", "95-99c")


def bucket(values: Iterable[float], edges: Sequence[float], labels: Sequence[str]) -> pd.Series:
    """Left-closed buckets [e_i, e_{i+1}) as an ordered categorical (NaN stays NaN)."""
    v = pd.Series(np.asarray(list(values), dtype=float))
    return pd.cut(v, list(edges), labels=list(labels), right=False)


def tau_bucket(tau_s: Iterable[float]) -> pd.Series:
    return bucket(tau_s, TAU_EDGES_S, TAU_LABELS)


def z_bucket(abs_z: Iterable[float]) -> pd.Series:
    return bucket(np.abs(np.asarray(list(abs_z), dtype=float)), Z_EDGES, Z_LABELS)


def price_bucket(px_dollars: Iterable[float]) -> pd.Series:
    return bucket(100.0 * np.asarray(list(px_dollars), dtype=float), PRICE_EDGES_C, PRICE_LABELS)


# ----------------------------------------------------------------------------- inference
@dataclass(frozen=True)
class CI:
    mean: float
    lo: float
    hi: float
    clusters: int

    def as_dict(self, prefix: str) -> dict[str, float]:
        return {prefix: self.mean, f"{prefix}_lo": self.lo, f"{prefix}_hi": self.hi}


def _cluster_sums(values: np.ndarray, weights: np.ndarray, clusters: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    keys, inv = np.unique(clusters.astype(str), return_inverse=True)
    s = np.bincount(inv, weights=values * weights, minlength=len(keys))
    w = np.bincount(inv, weights=weights, minlength=len(keys))
    return keys, s, w


def cluster_mean_ci(values: Sequence[float], weights: Sequence[float] | None, clusters: Sequence[Any],
                    n_boot: int = 500, seed: int = 11) -> CI:
    """Weighted mean sum(v w)/sum(w) with a 95% percentile CI from resampling clusters
    (settlement events) with replacement. NaN values are dropped."""
    v = np.asarray(values, dtype=float)
    w = np.ones_like(v) if weights is None else np.asarray(weights, dtype=float)
    c = np.asarray(clusters)
    ok = np.isfinite(v) & np.isfinite(w) & (w > 0)
    v, w, c = v[ok], w[ok], c[ok]
    if not len(v) or w.sum() <= 0:
        return CI(math.nan, math.nan, math.nan, 0)
    _, s, ws = _cluster_sums(v, w, c)
    mean = float(s.sum() / ws.sum())
    k = len(s)
    if k < 2:
        return CI(mean, math.nan, math.nan, k)
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, k, size=(n_boot, k))
    num = s[idx].sum(axis=1)
    den = ws[idx].sum(axis=1)
    bs = num[den > 0] / den[den > 0]
    lo, hi = np.percentile(bs, [2.5, 97.5]) if len(bs) else (math.nan, math.nan)
    return CI(mean, float(lo), float(hi), k)


def paired_diff_ci(a: pd.DataFrame, b: pd.DataFrame, value: str, weight: str = "contracts", cluster: str = "event",
                   n_boot: int = 500, seed: int = 17) -> CI:
    """CI of [weighted mean of `value` in b] - [same in a], resampling the UNION of clusters
    jointly (paired design: both arms replay the same events). An event with no fills in one
    arm contributes nothing to that arm's numerator or denominator."""
    def sums(df: pd.DataFrame) -> dict[str, tuple[float, float]]:
        if df is None or not len(df):
            return {}
        d = df[np.isfinite(df[value].to_numpy(dtype=float))]
        keys, s, w = _cluster_sums(d[value].to_numpy(dtype=float), d[weight].to_numpy(dtype=float),
                                   d[cluster].to_numpy())
        return {k: (si, wi) for k, si, wi in zip(keys, s, w)}

    sa, sb = sums(a), sums(b)
    keys = sorted(set(sa) | set(sb))
    if not keys:
        return CI(math.nan, math.nan, math.nan, 0)
    A = np.array([sa.get(k, (0.0, 0.0)) for k in keys])
    B = np.array([sb.get(k, (0.0, 0.0)) for k in keys])

    def diff(ix: np.ndarray | slice) -> np.ndarray | float:
        an, ad = A[ix, 0].sum(axis=-1), A[ix, 1].sum(axis=-1)
        bn, bd = B[ix, 0].sum(axis=-1), B[ix, 1].sum(axis=-1)
        with np.errstate(invalid="ignore", divide="ignore"):
            return bn / bd - an / ad

    full = diff(slice(None))
    k = len(keys)
    if k < 2:
        return CI(float(full), math.nan, math.nan, k)
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, k, size=(n_boot, k))
    an, ad = A[idx, 0].sum(axis=1), A[idx, 1].sum(axis=1)
    bn, bd = B[idx, 0].sum(axis=1), B[idx, 1].sum(axis=1)
    ok = (ad > 0) & (bd > 0)
    bs = bn[ok] / bd[ok] - an[ok] / ad[ok]
    lo, hi = np.percentile(bs, [2.5, 97.5]) if len(bs) else (math.nan, math.nan)
    return CI(float(full), float(lo), float(hi), k)


def net_ci(df: pd.DataFrame, n_boot: int = 500, seed: int = 11) -> CI:
    """Realized net cents per contract of settled fills (ledger DataFrame), event-clustered CI."""
    if df is None or not len(df):
        return CI(math.nan, math.nan, math.nan, 0)
    d = df[df["settle"].notna()] if "settle" in df else df
    return cluster_mean_ci(d["net_c_per_ct"], d["contracts"], d["event"], n_boot, seed)


def segment_rows(df: pd.DataFrame, by: list[str], days: float, n_boot: int = 300, seed: int = 11,
                 markout_cols: Sequence[str] = ("mo_10s_c", "mo_60s_c")) -> pd.DataFrame:
    """Per-segment table from a ledger-like DataFrame (settled fills): fills, contracts/day,
    realized net c/contract with event-bootstrap CI, gross edge, fees, markouts, toxic share."""
    rows = []
    if df is None or not len(df):
        return pd.DataFrame()
    for key, g in df.groupby(by, observed=True, sort=True):
        key = key if isinstance(key, tuple) else (key,)
        ci = cluster_mean_ci(g["net_c_per_ct"], g["contracts"], g["event"], n_boot, seed)
        ct = float(g["contracts"].sum())
        row = {**dict(zip(by, key)), "fills": len(g), "contracts": ct, "events": int(g["event"].nunique()),
               "fills_per_day": len(g) / days if days > 0 else math.nan,
               "contracts_per_day": ct / days if days > 0 else math.nan,
               "net_c": ci.mean, "net_lo_c": ci.lo, "net_hi_c": ci.hi,
               "gross_edge_c": float(np.average(g["gross_edge_c"], weights=g["contracts"])) if ct > 0 else math.nan,
               "fee_c": 100.0 * float(g["fee"].sum()) / ct if ct > 0 else math.nan,
               "net_usd_per_day": float(g["net"].sum()) / days if days > 0 else math.nan}
        for c in markout_cols:
            if c in g:
                ok = g[c].notna()
                row[c] = float(np.average(g.loc[ok, c], weights=g.loc[ok, "contracts"])) if ok.any() else math.nan
        if "mo_10s_c" in g and "gross_edge_c" in g:
            # markout vs the FILL PRICE at 10 s net of fees: (F_fill - px) s + (F_10s - F_fill) s - fee
            ok = g["mo_10s_c"].notna() & g["gross_edge_c"].notna()
            net10 = g.loc[ok, "gross_edge_c"] + g.loc[ok, "mo_10s_c"] - 100.0 * g.loc[ok, "fee"] / g.loc[ok, "contracts"]
            row["toxic_share"] = float((net10 < 0).mean()) if ok.any() else math.nan
        rows.append(row)
    return pd.DataFrame(rows)


def flag_only_A(table: pd.DataFrame, keys: Sequence[str], lo_col: str = "net_lo_c", policy_col: str = "policy") -> pd.DataFrame:
    """Add ``holds_only_under_A``: True where the policy-A row of a key has CI lower bound > 0
    but the B or C row does not (such a result is rejected: docs/TEST_MATRIX.md)."""
    t = table.copy()
    t["holds_only_under_A"] = False
    if policy_col not in t or lo_col not in t or not len(t):
        return t
    keys = [k for k in keys if k in t.columns]
    groups = t.groupby(keys, observed=True, dropna=False) if keys else [((), t)]
    for _, g in groups:
        a = g[g[policy_col] == "A"]
        bc = g[g[policy_col].isin(["B", "C"])]
        if len(a) and len(bc) and (a[lo_col] > 0).any() and not (bc[lo_col] > 0).all():
            t.loc[g.index, "holds_only_under_A"] = True
    return t


# ----------------------------------------------------------------------------- reports
def write_csv(df: pd.DataFrame, path: str | Path, synthetic: bool) -> None:
    """CSV with a leading ``synthetic`` column when the source recording is synthetic."""
    d = df.copy()
    if synthetic:
        d.insert(0, "synthetic", True)
    d.to_csv(path, index=False, float_format="%.6g")


def git_commit() -> str:
    try:
        return subprocess.run(["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"], capture_output=True,
                              text=True, timeout=5).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def _fmt_cell(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, (float, np.floating)):
        if not math.isfinite(float(v)):
            return "nan" if math.isnan(float(v)) else ("inf" if v > 0 else "-inf")
        a = abs(float(v))
        if a != 0 and (a >= 1e6 or a < 1e-3):
            return f"{float(v):.3g}"
        return f"{float(v):.4g}" if a < 100 else f"{float(v):.1f}"
    if isinstance(v, tuple):
        return "(" + ", ".join(_fmt_cell(x) for x in v) + ")"
    return str(v).replace("|", "/")


def markdown_table(df: pd.DataFrame, max_rows: int = 60) -> str:
    """Plain GitHub-markdown table (no external dependency)."""
    if df is None or not len(df):
        return "_(empty)_\n"
    d = df.head(max_rows)
    cols = [str(c) for c in d.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in d.iterrows():
        lines.append("| " + " | ".join(_fmt_cell(r[c]) for c in d.columns) + " |")
    if len(df) > max_rows:
        lines.append(f"\n_({len(df) - max_rows} more rows in the CSV)_")
    return "\n".join(lines) + "\n"


@dataclass
class Report:
    """CSV per table + one short markdown file per experiment.

    ``synthetic`` adds SYNTHETIC_BANNER at the top of the markdown and a ``synthetic`` column
    to every CSV so a table can never be mistaken for evidence.
    """

    name: str
    title: str
    out_dir: Path
    synthetic: bool = False
    rule: str = ""
    meta: dict[str, Any] = field(default_factory=dict)
    tables: list[tuple[str, pd.DataFrame, str]] = field(default_factory=list)
    lines: list[str] = field(default_factory=list)
    verdict: str = ""

    def table(self, key: str, df: pd.DataFrame, note: str = "") -> None:
        self.tables.append((key, df if df is not None else pd.DataFrame(), note))

    def line(self, text: str) -> None:
        self.lines.append(text)

    def write(self) -> Path:
        out = Path(self.out_dir)
        out.mkdir(parents=True, exist_ok=True)
        for key, df, _ in self.tables:
            d = df.copy()
            if self.synthetic:
                d.insert(0, "synthetic", True)
            d.to_csv(out / f"{self.name}_{key}.csv", index=False, float_format="%.6g")
        md = [f"# {self.title}", ""]
        if self.synthetic:
            md += [SYNTHETIC_NOTE, ""]
        if self.meta:
            md.append("| run | |")
            md.append("|---|---|")
            for k, v in self.meta.items():
                md.append(f"| {k} | {_fmt_cell(v)} |")
            md.append("")
        if self.rule:
            md += [f"**Decision rule (docs/TEST_MATRIX.md):** {self.rule}", ""]
        if self.verdict:
            v = self.verdict + (" _(synthetic: pipeline check only, not a trading decision)_" if self.synthetic else "")
            md += [f"**Verdict:** {v}", ""]
        md += [f"- {x}" for x in self.lines]
        if self.lines:
            md.append("")
        for key, df, note in self.tables:
            md += [f"## {key}", ""]
            if note:
                md += [note, ""]
            md.append(markdown_table(df))
            md.append(f"CSV: `{self.name}_{key}.csv`")
            md.append("")
        path = out / f"{self.name}.md"
        path.write_text("\n".join(md))
        return path


def verdict_from_ci(lo: float, hi: float, threshold: float = 0.0) -> str:
    """'ACCEPT' if lo > threshold, 'REJECT' if hi < threshold, else 'INCONCLUSIVE'."""
    if math.isfinite(lo) and lo > threshold:
        return "ACCEPT"
    if math.isfinite(hi) and hi < threshold:
        return "REJECT"
    return "INCONCLUSIVE"
